### ISSUE TITLE
License

### ISSUE THREAD

**Issue by craze3** [xsalazar/emoji-kitchen#475]
Hey @xsalazar would you mind adding a license.md? 🙏

**Comment by xsalazar** [comment]
Morning @craze3! I'm not sure what information you're looking for, but I don't own nor claim the images on the Emoji Kitchen website. This repository is just the website behind them that I made to showcase the images from Google.

Unfortunately you'll need to reach out to someone from Google to ask about licensing and whatnot.

You're free to fork this repo if you're interested in the website bits though :)

**Comment by anknetau** [comment]
Hi @xsalazar! Great work! Based on experience (and out of an abundance of caution) you should probably:

1. Add a license for this fantastic code you produced, so that others can understand whether it can be used for their own purposes/etc. (i.e., can I use this code in my own project, can I redistribute it, etc?)
2. Clarify in the README that the emoji themselves are not included (of course!) so that people are not confused either, and that this is not an official Google project.

I am not a lawyer but happy to help if you need some help - although I can tell you are a senior technologist, so feel free to ignore this 😊
