### ISSUE TITLE
Missing metadata.json, no mention of it in README.md

### ISSUE THREAD

**Issue by pattrickrice** [xsalazar/emoji-kitchen#649]
<img width="916" alt="Screenshot 2024-02-29 at 10 53 54 AM" src="https://github.com/xsalazar/emoji-kitchen/assets/20763171/e4a1441e-40eb-4588-a861-ea90ba723cc9">

**Comment by xsalazar** [comment]
👋 Hey Patrick! I recently moved this file to be downloaded during the deploy pipeline because it's such a huge file.

I forgot to point this out somewhere because I still have a local copy, sorry!!

Feel free to grab the data from: https://backend.emojikitchen.dev

I'll try to get the README updated this weekend with a sample `curl` command for others getting this set up.

The motivation here was to finally decouple the backend and frontend code, since there's now a separate service powering the search functionality that utilizes the same data 🙇
