### ISSUE TITLE
Please add the bicycle emoji

### ISSUE THREAD

**Issue by Coehill** [xsalazar/emoji-kitchen#854]

**Comment by xsalazar** [comment]
🚲 Hey @Coehill! You're in luck, because the Emoji Kitchen does indeed have support for the bike emoji!

Be sure you're visiting the website at https://emojikitchen.dev/ for the full, comprehensive experience :)

![image](https://github.com/user-attachments/assets/714b1660-291e-4763-91ab-8b89c94017ef)
